SanaeiBot/urls.py
from django.contrib import admin
from django.urls import path, include
from bot import views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webhook/', views.webhook, name='webhook'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path(r'', RedirectView.as_view(url='accounts/home/bot/')),
    path('finance/', include('finance.urls', namespace='finance')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('servers/', include('servers.urls', namespace='servers')),
    path("configs/", include("configs.urls", namespace='configs')),
    path("sellers/",include("sellers.urls", namespace='sellers')),
    path("log/", include("logs.urls", namespace='logs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bot/urls.py
from django.urls import path
from . import views

app_name = "bot"

urlpatterns = [

]

configs/urls.py
from django.urls import path
from . import views

app_name = "configs"


urlpatterns = [
    path("bot_create_config/<str:form_type>/", views.BotCreateConfigView.as_view(), name="bot_create_config"),
    path("bot_renew_config/<uuid:config_uuid>/<str:form_type>/", views.BotRenewConfigView.as_view(), name="bot_renew_config"),
    path("bot_change_config/<uuid:config_uuid>/", views.BotChangeConfigPage.as_view(), name="bot_change_config"),
    path("bot_list_config/<int:page>/", views.BotListConfigView.as_view(), name="bot_list_config"),
    path("config_page/<str:config_uuid>/", views.ConfigPage.as_view(), name="conf_page"),
    path("client_config_page/<str:config_uuid>/", views.ClientsConfigPage.as_view(), name="client_config_page"),
    path('delete_config/<str:config_uuid>/',views.DeleteConfig.as_view(), name="delete_config"),
    path('disable_config/<str:config_uuid>/<int:enable>/',views.DisableConfig.as_view(), name="disable_config"),
    path("change_unlimit_limit/<uuid:config_uuid>/<int:is_bot>/", views.ChangeUnlimitLimitView.as_view(), name="change_unlimit_limit"),


    path("api_get_config_time_chices/", views.ApiGetConfigTimeChoices.as_view(), name="api_get_time_choices"),
    path("api_get_config_usage_chices/", views.ApiGetConfigUsageChoices.as_view(), name="api_get_usage_choices"),
    path("api_get_config_ip_limit_chices/", views.ApiGetConfigIPLimitChoices.as_view(), name="api_get_iplimit_choices"),
    path("api_get_axact_price/", views.ApiGetConfigPriceChoices.as_view(), name="api_get_axact_price"),


    path("sublink/<uuid:config_uuid>/", views.Sublink.as_view(), name="sublink"),

    path("sellers/create/<str:username>/<str:form_type>/", views.SellersCreateConfigView.as_view(),name="seller_create"),
    path("sellers/list/<str:username>/", views.SellersListConfigView.as_view(),name="seller_list"),
    path("sellers/change_config/<uuid:config_uuid>/", views.SellersChangeConfigPage.as_view(), name="sellers_change_config"),
    path("sellers_config_page/<str:config_uuid>/", views.SellersConfigPage.as_view(), name="sellers_conf_page"),
    path("sellers_renew_page/<str:config_uuid>/<str:form_type>/", views.SellersRenewConfigView.as_view(), name="sellers_renew"),
    path("sellers/disable_all_services/", views.DisableAllService.as_view(), name="sellers_disable_all_services"),


    path("sellers_api_get_config_time_chices/", views.ApiSellersGetConfigTimeChoices.as_view(), name="seller_api_get_time_choices"),
    path("sellers_api_get_config_usage_chices/", views.ApiSellersGetConfigUsageChoices.as_view(), name="seller_api_get_usage_choices"),
    path("sellers_api_get_config_ip_limit_chices/", views.ApiSellersGetConfigIPLimitChoices.as_view(), name="seller_api_get_iplimit_choices"),
    path("sellers_api_get_axact_price/", views.ApiSellersGetConfigPriceChoices.as_view(), name="seller_api_get_axact_price"),

    path("CreateAllConfigsInAllServers/", views.CreateAllConfigsInAllServers.as_view(), name="CreateAllConfigsInAllServers"),


    path("delete_service_by_force/<str:name>/", views.DeleteServiceByForce.as_view(), name="delete_service_by_force"),
]

servers/urls.py
from django.urls import path
from . import views
from .sanaie_api import ServerApi
app_name = "servers"

urlpatterns = [
    path('show_servers/', views.ShowServers.as_view(), name="show_servers"),
    path("add_server/", views.AddServer.as_view(), name="add_server"),
    path("edit_server/<int:server_id>/", views.EditServer.as_view(), name="edit_server"),
]

servers/models.py
from django.db import models
from django.db.models import PositiveIntegerField


class Server(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    url = models.URLField()
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    inbound_id = models.PositiveSmallIntegerField()
    active = models.BooleanField(default=True)
    maximum_connection = PositiveIntegerField(default=0)
    online_users = PositiveIntegerField(default=0)
    last_update = models.BigIntegerField(default=0)
    config_example = models.TextField(default='')
    copy_in_link = models.BooleanField(default=True)

servers/forms.py
from django import forms
from finance.models import Prices as PriceModel
from django.core.exceptions import ValidationError
from .models import Server



class CreateConfigForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["type"].choices = self.type_limit()
    def type_limit(self):
        types = [('limited','حجمی')]
        if PriceModel.objects.filter(usage_limit=0).exists():
            types.append(('usage_unlimit', "حجم نامحدود"))
        if PriceModel.objects.filter(expire_limit=0).exists():
            types.append(('time_unlimit', "زمان نامحدود"))
        return types


    type = forms.ChoiceField(required=False,)
    usage_limit = forms.CharField(required=False, widget=forms.Select(choices=[]))
    days_limit = forms.CharField(required=False, widget=forms.Select(choices=[]))
    ip_limit = forms.CharField(required=False, widget=forms.Select(choices=[]))
    paid = forms.BooleanField(required=False, initial=True)
    def clean_usage_limit(self):
        return self.cleaned_data.get('usage_limit')
    def clean_days_limit(self):
        return self.cleaned_data.get('days_limit')
    def clean_ip_limit(self):
        return self.cleaned_data.get('ip_limit')



class ManualCreateConfigForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["type"].choices = self.type_limit()
    def type_limit(self):
        types = [('limited','حجمی')]
        if PriceModel.objects.filter(usage_limit=0).exists():
            types.append(('usage_unlimit', "حجم نامحدود"))
        if PriceModel.objects.filter(expire_limit=0).exists():
            types.append(('time_unlimit', "زمان نامحدود"))
        return types



    type = forms.ChoiceField(required=False)
    usage_limit = forms.IntegerField(required=False)
    days_limit = forms.IntegerField(required=False)
    ip_limit = forms.ChoiceField(required=False, choices=[(1, '1 کاربره'), (2, '2 کاربره')])
    price = forms.IntegerField(required=False)
    paid = forms.BooleanField(required=False, initial=True)

    def clean_price(self):
        price = self.cleaned_data['price']
        if price is None:
            raise ValidationError('قیمت را وارد کنید.')
        elif not 0 <= price < 1500:
            raise ValidationError('قیمت باید بین 0 تا 1500 هزار تومان باشد.')
        return price

    def clean(self):
        type = self.cleaned_data.get('type')
        usage_limit = self.cleaned_data.get('usage_limit')
        days_limit = self.cleaned_data.get('days_limit')
        if type == "limited":
            if usage_limit is None:
                raise ValidationError('حجم کانفیگ را وارد کنید.')
            elif not 1 < usage_limit < 1000:
                raise ValidationError('حجم کانفیگ باید بین 1 تا 1000 گیگ باشد.')
            if days_limit is None:
                raise ValidationError('مدت زمان کانفیگ را وارد کنید.')
            elif not 0 < days_limit < 365:
                raise ValidationError('مدت زمان کانفیگ باید بین 1 روز تا 365 روز باشد.')
        elif type == 'usage_unlimit':
            if days_limit is None:
                raise ValidationError('مدت زمان کانفیگ را وارد کنید.')
            elif not 0 < days_limit < 365:
                raise ValidationError('مدت زمان کانفیگ باید بین 1 روز تا 365 روز باشد.')
        elif type == 'time_unlimit':
            if usage_limit is None:
                raise ValidationError('حجم کانفیگ را وارد کنید.')
            elif not 1 < usage_limit < 1000:
                raise ValidationError('حجم کانفیگ باید بین 1 تا 1000 گیگ باشد.')



class ChangeConfigSettingForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.config_data = kwargs.pop('config_data', None)
        super().__init__(*args, **kwargs)
        if self.config_data:
            self.fields["usage_limit"].initial = self.config_data["usage"]
            self.fields["days_limit"].initial = int(self.config_data["expire_time"]) + 1
            self.fields["ip_limit"].initial = self.config_data["ip_limit"]

    usage_limit = forms.IntegerField(required=False)
    days_limit = forms.IntegerField(required=False)
    ip_limit = forms.IntegerField(required=False)

    def clean(self):
        usage_limit = self.cleaned_data.get('usage_limit')
        days_limit = self.cleaned_data.get('days_limit')
        ip_limit = self.cleaned_data.get("ip_limit")
        if usage_limit is None:
            raise ValidationError('حجم کانفیگ را وارد کنید.')
        elif not 0 <= usage_limit < 1000:
            raise ValidationError('حجم کانفیگ باید بین 1 تا 1000 گیگ باشد.')
        if days_limit is None:
            raise ValidationError('مدت زمان کانفیگ را وارد کنید.')
        elif not 0 <= days_limit < 181:
            raise ValidationError('مدت زمان کانفیگ باید بین 1 تا 180 روز باشد.')
        if not 0 <= ip_limit <= 4:
            raise ValidationError('محدودیت آی پی باید بین 0 تا 4 باشد.')


class AddServerForm(forms.Form):
    ID = forms.IntegerField(required=True)
    server_name = forms.CharField(max_length=30, required=True)
    server_url = forms.CharField(max_length=60, required=True)
    username = forms.CharField(max_length=30, required=True)
    password = forms.CharField(max_length=30, required=True)
    inbound_id = forms.IntegerField(required=True)
    active = forms.BooleanField(initial=True, required=False)
    maximum_connection = forms.IntegerField(required=False, initial=0)
    config_example = forms.CharField(widget=forms.Textarea, required=True)
    copy_in_link = forms.BooleanField(required=False, initial=True)

    def clean_server_url(self):
        url = self.cleaned_data['server_url']
        if not url.startswith('http') or not url.endswith("/") or "panel/" in url:
            raise ValidationError("url اشتباه است.")
        return url


class EditServerForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.server_id = kwargs.pop('server_id', None)
        super().__init__(*args, **kwargs)
        server = Server.objects.get(id=self.server_id)
        self.fields["server_name"].initial = server.name
        self.fields["server_url"].initial = server.url
        self.fields["username"].initial = server.username
        self.fields["password"].initial = server.password
        self.fields["inbound_id"].initial = server.inbound_id
        self.fields["active"].initial = server.active
        self.fields["maximum_connection"].initial = server.maximum_connection
        self.fields["config_example"].initial = server.config_example
        self.fields["copy_in_link"].initial = server.copy_in_link

    server_name = forms.CharField(max_length=30, required=True)
    server_url = forms.CharField(max_length=60, required=True)
    username = forms.CharField(max_length=30, required=True)
    password = forms.CharField(max_length=30, required=True)
    inbound_id = forms.IntegerField(required=True)
    active = forms.BooleanField(initial=True, required=False)
    maximum_connection = forms.IntegerField(required=False)
    config_example = forms.CharField(widget=forms.Textarea, required=True)
    copy_in_link = forms.BooleanField(required=False)


    def clean_server_url(self):
        url = self.cleaned_data['server_url']
        if not url.startswith('http') or not url.endswith("/") or "panel/" in url:
            raise ValidationError("url اشتباه است.")
        return url

servers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from .models import Server
from django.views import View
from .forms import AddServerForm, EditServerForm
import re



class ShowServers(LoginRequiredMixin, View):
    def get(self, request):
        obj = Server.objects.all()
        return render(request, "show_servers.html", {'servers': obj})


class AddServer(LoginRequiredMixin, View):
    def get(self, request):
        form = AddServerForm()
        return render(request, "add_server.html", {'form': form})

    def post(self, request):
        form = AddServerForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            regex = r"\w{8}-\w{4}-\w{4}-\w{4}-\w{12}"
            config_text:str = cd["config_example"].split("#")[0] + "#"
            matches = re.search(regex, config_text)
            print(type(matches.group()))
            Server.objects.create(
                id=cd["ID"],
                name=cd["server_name"],
                url=cd["server_url"],
                username=cd["username"],
                password=cd["password"],
                inbound_id=cd["inbound_id"],
                active=cd["active"],
                copy_in_link=cd["copy_in_link"],
                maximum_connection=cd["maximum_connection"],
                config_example=config_text.replace(matches.group(), "uuid"),
            ).save()
            return redirect('servers:show_servers')
        return render(request, "add_server.html", {'form': form})


class EditServer(LoginRequiredMixin, View):
    def get(self, request, server_id):
        form = EditServerForm(server_id=server_id)
        return render(request, "add_server.html", {'form': form})

    def post(self, request, server_id):
        form = EditServerForm(request.POST, server_id=server_id)
        if form.is_valid():
            regex = r"\w{8}-\w{4}-\w{4}-\w{4}-\w{12}"
            cd = form.cleaned_data
            config_example = (cd["config_example"].split("#")[0]) + "#"
            if not "uuid" in config_example:
                matches = re.search(regex, config_example)
                config_example = config_example.replace(matches.group(), "uuid")

            obj = Server.objects.get(id=server_id)
            obj.name = cd["server_name"]
            obj.url = cd["server_url"]
            obj.username = cd["username"]
            obj.password = cd["password"]
            obj.inbound_id = cd["inbound_id"]
            obj.active = cd["active"]
            obj.copy_in_link = cd["copy_in_link"]
            obj.maximum_connection = cd["maximum_connection"]
            obj.config_example = config_example
            obj.save()
            return redirect('servers:show_servers')
        return render(request, "add_server.html", {'form': form, "edit": True})


# class DeleteServer(LoginRequiredMixin):
#     def get(self, request, serverid):
#         server_obj = Server.objects.get(id=serverid)

servers/templates/add_server.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'configs/create_config.css' %}?{% now "d" %}">
</head>
<body>
{% include "navbar_bot.html" %}
{% include 'messages.html' %}
<div id="main">
        <form novalidate action="" method="post" dir="ltr">
            {% for field_errors in form.errors.values %}
              {% for error in field_errors %}
                  <p dir="rtl" class="errors">{{ error }}</p>
              {% endfor %}
            {% endfor %}
            <h3 id="title">Add Server</h3>
            {% csrf_token %}
            {% if not edit %}
                <div id="time_limit" class="textinput item"><h3 class="item_text">server ID: </h3>{{ form.ID }}</div>
            {% endif %}
            <div id="time_limit" class="textinput item"><h3 class="item_text">server name: </h3>{{ form.server_name }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">Url: </h3>{{ form.server_url }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text"> Username: </h3>{{ form.username }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">Password: </h3>{{ form.password }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">Inbound id: </h3>{{ form.inbound_id }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">Active: </h3>{{ form.active }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">copy_in_link: </h3>{{ form.copy_in_link }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">maximum connection: </h3>{{ form.maximum_connection }} 0 = unlimited</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">config example: </h3>{{ form.config_example }}</div>
            <input id="create" type="submit" class="submit_btn" value="Change">
        </form>
    </div>
{% include "loading.html" %}

</body>
</html>

servers/templates/renew_config.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'servers/create_config.css' %}">
</head>
<body>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        let type = document.querySelector('#id_type');
        let usage = document.querySelector('#usage');
        let time_limit = document.querySelector("#time_limit")
        let ip_limit = document.querySelector('#ip_limit')
        function toggleexpireField() {
            if (type.value === "limited") {
                time_limit.style.display = "block"
                usage.style.display = "block"
                ip_limit.style.display = "none"
            }
            else if (type.value === 'time_unlimit') {
                time_limit.style.display = "none"
                usage.style.display = "block"
                ip_limit.style.display = "none"
            }
            else if (type.value === 'usage_unlimit'){
                time_limit.style.display = "block"
                usage.style.display = "none"
                ip_limit.style.display = "block"
            }
        }

        type.addEventListener('change', toggleexpireField);
        toggleexpireField();
    });
</script>
{% include "navbar.html" %}
{% include 'messages.html' %}
<div id="main">
    <div id="zx">
    {% if form_type == 'auto' %}
        <a href="{% url 'servers:renew_page' config.config_uuid 'manual' %}" class="change_form">کانفیگ دستی</a>
    {% else %}
        <a href="{% url 'servers:renew_page' config.config_uuid 'auto' %}" class="change_form">کانفیگ خودکار</a>
    {% endif %}
    </div>
        <form novalidate action="" method="post" dir="rtl">
            {% for field_errors in form.errors.values %}
              {% for error in field_errors %}
                  <p dir="rtl" class="errors">{{ error }}</p>
              {% endfor %}
            {% endfor %}
            <h3 id="title">تمدید سرویس</h3>
            <a href="{% url "servers:conf_page" config.server.server_id config.config_uuid config.config_name %}" id="title" class="tamdid_conf">{{ config.config_name }}</a>
            {% csrf_token %}
            <div class="textinput item"><h3 class="item_text">نوع کانفیگ : </h3>{{ form.type }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">مدت زمان کانفیگ : </h3>{{ form.days_limit }} {% if form_type == "manual" %}🔺 روز{% endif %}</div>
            <div id="usage" class="textinput item"><h3 class="item_text">حجم کانفیگ : </h3>{{ form.usage_limit }} {% if form_type == "manual" %}GB{% endif %}</div>
            <div id="ip_limit" class="textinput item"><h3 class="item_text">تعداد کاربر : </h3>{{ form.ip_limit }}</div>
            {% if form_type == 'auto' %}
            <h3 class="item_text" dir="ltr" style="display:inline-block; ">: قیمت<div class="loader2" dir="ltr" id="price_loading"></div><h4 id="pricespan"> </h4></h3>
            <div id="divloader" style="display: flex; align-items: center"><div class="loader" id="subloader"></div></div>
            {% else %}
            <div id="price" class="textinput item"><h3 class="item_text"> قیمت : </h3>{{ form.price }} هزار تومان</div>
            {% endif %}
            <div id="paid" class="textinput item paid_text">پرداخت شده : {{ form.paid }}</div>
            <input id="create" type="submit" value="Create" class="submit_btn">
        {% if form_type == "auto" %}
            <script>
    const days_limit = document.getElementById('id_days_limit');
    const usage_limit = document.getElementById('id_usage_limit');
    const type = document.getElementById('id_type');
    const ip_limit = document.getElementById('id_ip_limit');
    const h3Element = document.getElementById('pricespan');
    const submitButton = document.getElementById('create');
    const subloader = document.getElementById('subloader');
    const priceloading = document.getElementById('price_loading');
    function fetchTimeChoices() {
        days_limit.disabled = true;
        usage_limit.disabled = true;
        ip_limit.disabled = true;
        submitButton.style.display = 'none';
        subloader.style.display = 'block';
        priceloading.style.display = 'block';
        const otherField2Value = type.value;
        const url = `{% url "servers:api_get_time_choices" %}?type=${otherField2Value}`;
        h3Element.textContent = ``;
        fetch(url)
            .then(response => response.json())
            .then(data => {
                {#h3Element.textContent = data;#}
                days_limit.innerHTML = '';
                data.choices.forEach(choice => {
                    const option = document.createElement('option');
                    option.value = choice[0];
                    option.text = choice[1];
                    days_limit.add(option);

                });
                submitButton.style.display = 'block';
                subloader.style.display = 'none';
                days_limit.disabled = false;
                fetchUsageChoices()
            });

    }
    function fetchUsageChoices() {
        usage_limit.disabled = true;
        ip_limit.disabled = true;
        submitButton.style.display = 'none';
        subloader.style.display = 'block';
        priceloading.style.display = 'block';
        const otherField2Value = type.value;
        const otherField1Value = days_limit.value;
        const url = `{% url "servers:api_get_usage_choices" %}?type=${otherField2Value}&time=${otherField1Value}`;
        h3Element.textContent = ``;
        fetch(url)
            .then(response => response.json())
            .then(data => {
                {#h3Element.textContent = data;#}
                usage_limit.innerHTML = '';
                data.choices.forEach(choice => {
                    const option = document.createElement('option');
                    option.value = choice[0];
                    option.text = choice[1];
                    usage_limit.add(option);

                });
                submitButton.style.display = 'block';
                subloader.style.display = 'none';
                usage_limit.disabled = false;
                fetchIPLimitChoices()
            });

    }
    function fetchIPLimitChoices() {
        submitButton.style.display = 'none';
        ip_limit.disabled = true;
        subloader.style.display = 'block';
        priceloading.style.display = 'block';
        const otherField2Value = type.value;
        const otherField1Value = days_limit.value;
        const url = `{% url "servers:api_get_iplimit_choices" %}?type=${otherField2Value}&time=${otherField1Value}`;
        h3Element.textContent = ``;
        fetch(url)
            .then(response => response.json())
            .then(data => {
                {#h3Element.textContent = data;#}
                ip_limit.innerHTML = '';
                data.choices.forEach(choice => {
                    const option = document.createElement('option');
                    option.value = choice[0];
                    option.text = choice[1];
                    ip_limit.add(option);
                    ip_limit.disabled = false;
                });
                submitButton.style.display = 'block';
                subloader.style.display = 'none';

                price();
            });

    }
    function price() {
        days_limit.disabled = false;

        priceloading.style.display = 'block';
        const otherField1Value = usage_limit.value;
        const otherField2Value = type.value;
        const otherField3Value = days_limit.value;
        const otherField4Value = ip_limit.value;
        const url = `{% url "servers:api_get_axact_price" %}?usage=${otherField1Value}&type=${otherField2Value}&time=${otherField3Value}&iplimit=${otherField4Value}`;
        h3Element.textContent = ``;
        fetch(url)
            .then(response => response.json())
            .then(data => {
                    h3Element.textContent = `T ${data.price}`;
                    priceloading.style.display = 'none';
                    submitButton.style.display = 'block';
            });

    }
    fetchTimeChoices();
    type.addEventListener('change', fetchTimeChoices);
    days_limit.addEventListener('change', fetchUsageChoices)
    usage_limit.addEventListener('change', fetchIPLimitChoices);
    ip_limit.addEventListener('change', price);
</script>
        {% endif %}
        </form>
    </div>
{% include "loading.html" %}
{% include "list_servers.html" %}

</body>
</html>

servers/templates/show_servers.html
{% load compress %}
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'servers/show_servers.css' %}?{% now "d" %}">
</head>

<body dir="ltr">
    {% include "navbar_bot.html" %}
    {% include 'messages.html' %}
<div id="main">
    <div id="main">
        <h2 id="header">
            Servers
        </h2>
        <div id="x">
            <a href="{% url "servers:add_server" %}" id="add_server_btn">Add Server</a>
        </div>
        <div class="servers_list">
            {% for server in servers %}
                <div class="server_item">
                    <h3 class="server_url">ID = <span class="cspan">{{ server.id }}</span></h3>
                    <h3 class="server_url">server name: <span class="cspan">{{ server.name }}</span></h3>
                    <h3 class="server_url">server url: <span class="cspan">{{ server.url }}</span></h3>
                    <h3 class="server_url">inbound id: <span class="cspan">{{ server.inbound_id }}</span></h3>

                    {% if server.active %}
                    	<h3 dir="ltr" class="server_url">Active: <span class="cspan">  ✅</span> </h3>
                     {% else %}
                        <h3 dir="ltr" class="server_url">Active: ❌</h3>
                    {% endif %}
                    {% if server.copy_in_link %}
                    	<h3 dir="ltr" class="server_url">Vless: <span class="cspan">  ✅</span></h3>
                     {% else %}
                        <h3 dir="ltr" class="server_url">Vless:  ❌</h3>
                    {% endif %}
 
                    <div class="btnn" style="width: 100%">
                        <a class="edit_btn" href="{% url "servers:edit_server" server.id %}">Edit Server</a>
                    </div>
                </div>

            {% endfor %}
        </div>
    <h2 id="header" style="margin: 1rem 0 0">TEST SERVER</h2>
    <div class="servers_list">
                <a class="server_item" href="">
                    <h3 class="server_name"><span class="red_span"></span>{{ server_test }}</h3>
                </a>
    </div>
    </div>


</div>
{% include "loading.html" %}

</body>
</html>