SanaeiBot/urls.py
from django.contrib import admin
from django.urls import path, include
from bot import views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webhook/', views.webhook, name='webhook'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path(r'', RedirectView.as_view(url='accounts/home/bot/')),
    path('finance/', include('finance.urls', namespace='finance')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('servers/', include('servers.urls', namespace='servers')),
    path("configs/", include("configs.urls", namespace='configs')),
    path("sellers/",include("sellers.urls", namespace='sellers')),
    path("log/", include("logs.urls", namespace='logs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path("home/bot/", views.HomeBotView.as_view(), name='home_bot'),
    path("home/Sellers/", views.HomeSellersView.as_view(), name='home_sellers'),

    path("settings/", views.SettingsPage.as_view(), name='settings'),
    path("vpn_apps/", views.VpnAppsPage.as_view(), name='vpn_apps'),
    path("delete_app/<int:ind>/", views.DeleteAppPage.as_view(), name='delete_app'),
    path("add_vpn_app/", views.AddAppPage.as_view(), name='add_vpn_app'),
]

bot/urls.py
from django.urls import path
from . import views

app_name = "bot"

urlpatterns = [

]

configs/urls.py
from django.urls import path
from . import views

app_name = "configs"


urlpatterns = [
    path("bot_create_config/<str:form_type>/", views.BotCreateConfigView.as_view(), name="bot_create_config"),
    path("bot_renew_config/<uuid:config_uuid>/<str:form_type>/", views.BotRenewConfigView.as_view(), name="bot_renew_config"),
    path("bot_change_config/<uuid:config_uuid>/", views.BotChangeConfigPage.as_view(), name="bot_change_config"),
    path("bot_list_config/<int:page>/", views.BotListConfigView.as_view(), name="bot_list_config"),
    path("config_page/<str:config_uuid>/", views.ConfigPage.as_view(), name="conf_page"),
    path("client_config_page/<str:config_uuid>/", views.ClientsConfigPage.as_view(), name="client_config_page"),
    path('delete_config/<str:config_uuid>/',views.DeleteConfig.as_view(), name="delete_config"),
    path('disable_config/<str:config_uuid>/<int:enable>/',views.DisableConfig.as_view(), name="disable_config"),
    path("change_unlimit_limit/<uuid:config_uuid>/<int:is_bot>/", views.ChangeUnlimitLimitView.as_view(), name="change_unlimit_limit"),


    path("api_get_config_time_chices/", views.ApiGetConfigTimeChoices.as_view(), name="api_get_time_choices"),
    path("api_get_config_usage_chices/", views.ApiGetConfigUsageChoices.as_view(), name="api_get_usage_choices"),
    path("api_get_config_ip_limit_chices/", views.ApiGetConfigIPLimitChoices.as_view(), name="api_get_iplimit_choices"),
    path("api_get_axact_price/", views.ApiGetConfigPriceChoices.as_view(), name="api_get_axact_price"),


    path("sublink/<uuid:config_uuid>/", views.Sublink.as_view(), name="sublink"),

    path("sellers/create/<str:username>/<str:form_type>/", views.SellersCreateConfigView.as_view(),name="seller_create"),
    path("sellers/list/<str:username>/", views.SellersListConfigView.as_view(),name="seller_list"),
    path("sellers/change_config/<uuid:config_uuid>/", views.SellersChangeConfigPage.as_view(), name="sellers_change_config"),
    path("sellers_config_page/<str:config_uuid>/", views.SellersConfigPage.as_view(), name="sellers_conf_page"),
    path("sellers_renew_page/<str:config_uuid>/<str:form_type>/", views.SellersRenewConfigView.as_view(), name="sellers_renew"),
    path("sellers/disable_all_services/", views.DisableAllService.as_view(), name="sellers_disable_all_services"),


    path("sellers_api_get_config_time_chices/", views.ApiSellersGetConfigTimeChoices.as_view(), name="seller_api_get_time_choices"),
    path("sellers_api_get_config_usage_chices/", views.ApiSellersGetConfigUsageChoices.as_view(), name="seller_api_get_usage_choices"),
    path("sellers_api_get_config_ip_limit_chices/", views.ApiSellersGetConfigIPLimitChoices.as_view(), name="seller_api_get_iplimit_choices"),
    path("sellers_api_get_axact_price/", views.ApiSellersGetConfigPriceChoices.as_view(), name="seller_api_get_axact_price"),

    path("CreateAllConfigsInAllServers/", views.CreateAllConfigsInAllServers.as_view(), name="CreateAllConfigsInAllServers"),


    path("delete_service_by_force/<str:name>/", views.DeleteServiceByForce.as_view(), name="delete_service_by_force"),
]

customers/urls.py
from django.urls import path
from . import views

app_name = "customers"


urlpatterns = [
   path("custumers_list/", views.CustomerList.as_view(), name="custumers_list"),
   path("custumer_detail/<int:customer_id>/", views.CustomerDetail.as_view(), name="custumer_detail"),
   # path('custumer_configs_api/<str:config_uuid>/', views.GetCustumersConfigsAPI.as_view(), name="custumer_configs_api"),
   path("send_msg_to_all/", views.SendMsgToAllView.as_view(), name="send_msg_to_all"),
   path("send_msg_to_Custumer/<int:customer>/", views.SendMsgToCustomerView.as_view(), name="send_msg_to_customer"),
   path("change_wallet/<int:userid>/", views.ChangeWalletAmount.as_view(), name="change_wallet"),
   # path("update_customer/<int:userid>/", views.UpdateCustumer.as_view(), name="update_customer"),
   # path("register_conf_for_customer/<str:conf_uuid>/", views.RegisterConfigToCustumer.as_view(), name="register_conf_for_customer"),
   # path("ban_user/<int:userid>/<int:status>/", views.BanUser.as_view(), name="ban_user"),
]

configs/models.py
from django.db import models
from accounts.models import User
from customers.models import Customer
from servers.models import Server

class Service(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    uuid = models.UUIDField(unique=True)
    name = models.CharField(max_length=50, unique=True)
    usage_limit = models.IntegerField(default=0)
    usage = models.FloatField(default=0)
    expire_time = models.BigIntegerField(default=0)
    start_time = models.BigIntegerField(default=0)
    user_limit = models.SmallIntegerField(default=0)
    paid = models.BooleanField(default=True)
    status = models.SmallIntegerField(default=0, choices=[(0,'Active'), (1,'disable'), (2,'Ended'), (4,'deleting')])
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True) # null => main bot
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, related_name='created_by')
    price = models.PositiveBigIntegerField(null=True)
    infinit_limit = models.PositiveIntegerField(null=True, default=0)
    new_version = models.BooleanField(default=True)


class Config(models.Model):
    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    status = models.SmallIntegerField(default=-1, choices=[(-1,'not_created'),(1,'active'),(2,'disable'),(3,'deleted')])
    usage = models.FloatField(default=0)
    last_update = models.BigIntegerField(default=0)


class ConfigJobsQueue(models.Model):
    config = models.ForeignKey(Config, on_delete=models.CASCADE)
    job = models.IntegerField(choices=[(0, "create"), (1, "disable"), (2, "delete"), (3, "enable"), (4, "reset")])
    done = models.BooleanField(default=False)
    last_try = models.BigIntegerField(default=0)
    try_count = models.SmallIntegerField(default=0)
    by_user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, related_name='by_user')


class EndNotif(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    timestamp = models.PositiveBigIntegerField()
    type = models.SmallIntegerField(choices=[(0,"ended"),(1,"time"),(2,"usage")])

configs/forms.py
from django import forms
from finance.models import Prices, SellersPrices
from django.core.exceptions import ValidationError
from django.db.models import Q
from accounts.models import User


class SearchConfigForm(forms.Form):
    search_config = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Search Config Name or UUID'}))


class CreateConfigForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["type"].choices = self.type_limit()
    def type_limit(self):
        types = [('limited','حجمی')]
        if Prices.objects.filter(usage_limit=0).exists():
            types.append(('usage_unlimit', "حجم نامحدود"))
        if Prices.objects.filter(expire_limit=0).exists():
            types.append(('time_unlimit', "زمان نامحدود"))
        return types


    type = forms.ChoiceField(required=False,)
    usage_limit = forms.CharField(required=False, widget=forms.Select(choices=[]))
    days_limit = forms.CharField(required=False, widget=forms.Select(choices=[]))
    ip_limit = forms.CharField(required=False, widget=forms.Select(choices=[]))
    paid = forms.BooleanField(required=False, initial=True)
    def clean_usage_limit(self):
        return self.cleaned_data.get('usage_limit')
    def clean_days_limit(self):
        return self.cleaned_data.get('days_limit')
    def clean_ip_limit(self):
        return self.cleaned_data.get('ip_limit')



class ManualCreateConfigForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["type"].choices = self.type_limit()
    def type_limit(self):
        types = [('limited','حجمی')]
        if Prices.objects.filter(usage_limit=0).exists():
            types.append(('usage_unlimit', "حجم نامحدود"))
        if Prices.objects.filter(expire_limit=0).exists():
            types.append(('time_unlimit', "زمان نامحدود"))
        return types

    type = forms.ChoiceField(required=False)
    usage_limit = forms.IntegerField(required=False)
    days_limit = forms.IntegerField(required=False)
    ip_limit = forms.ChoiceField(required=False, choices=[(1, '1 کاربره'), (2, '2 کاربره')])
    price = forms.IntegerField(required=False)
    paid = forms.BooleanField(required=False, initial=True)

    def clean_price(self):
        price = self.cleaned_data['price']
        if price is None:
            raise ValidationError('قیمت را وارد کنید.')
        elif not 0 <= price < 1500:
            raise ValidationError('قیمت باید بین 0 تا 1500 هزار تومان باشد.')
        return price

    def clean(self):
        type = self.cleaned_data.get('type')
        usage_limit = self.cleaned_data.get('usage_limit')
        days_limit = self.cleaned_data.get('days_limit')
        if type == "limited":
            if usage_limit is None:
                raise ValidationError('حجم کانفیگ را وارد کنید.')
            elif not 1 < usage_limit < 1000:
                raise ValidationError('حجم کانفیگ باید بین 1 تا 1000 گیگ باشد.')
            if days_limit is None:
                raise ValidationError('مدت زمان کانفیگ را وارد کنید.')
            elif not 0 < days_limit < 365:
                raise ValidationError('مدت زمان کانفیگ باید بین 1 روز تا 365 روز باشد.')
        elif type == 'usage_unlimit':
            if days_limit is None:
                raise ValidationError('مدت زمان کانفیگ را وارد کنید.')
            elif not 0 < days_limit < 365:
                raise ValidationError('مدت زمان کانفیگ باید بین 1 روز تا 365 روز باشد.')
        elif type == 'time_unlimit':
            if usage_limit is None:
                raise ValidationError('حجم کانفیگ را وارد کنید.')
            elif not 1 < usage_limit < 1000:
                raise ValidationError('حجم کانفیگ باید بین 1 تا 1000 گیگ باشد.')


class ChangeConfigSettingForm(forms.Form):

    usage_limit = forms.IntegerField(required=False)
    days_limit = forms.IntegerField(required=False)
    ip_limit = forms.IntegerField(required=False)

    def clean(self):
        usage_limit = self.cleaned_data.get('usage_limit')
        days_limit = self.cleaned_data.get('days_limit')
        ip_limit = self.cleaned_data.get("ip_limit")
        if usage_limit is None:
            raise ValidationError('حجم کانفیگ را وارد کنید.')
        elif not 0 <= usage_limit < 1000:
            raise ValidationError('حجم کانفیگ باید بین 1 تا 1000 گیگ باشد.')
        if days_limit is None:
            raise ValidationError('مدت زمان کانفیگ را وارد کنید.')
        elif not 0 <= days_limit < 181:
            raise ValidationError('مدت زمان کانفیگ باید بین 1 تا 180 روز باشد.')
        if not 0 <= ip_limit <= 4:
            raise ValidationError('محدودیت آی پی باید بین 0 تا 4 باشد.')



###################################### sellers


class SellersCreateConfigForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.username = kwargs.pop('username')
        super().__init__(*args, **kwargs)
        self.fields["type"].choices = self.type_limit()
    def type_limit(self):
        types = []
        if SellersPrices.objects.filter(~Q(usage_limit=0), ~Q(expire_limit=0),seller__username=self.username).exists():
            types = [('limited','حجمی')]
        if SellersPrices.objects.filter(usage_limit=0, seller__username=self.username).exists():
            types.append(('usage_unlimit', "حجم نامحدود"))
        if SellersPrices.objects.filter(expire_limit=0, seller__username=self.username).exists():
            types.append(('time_unlimit', "زمان نامحدود"))
        return types


    type = forms.ChoiceField(required=False,)
    usage_limit = forms.CharField(required=False, widget=forms.Select(choices=[]))
    days_limit = forms.CharField(required=False, widget=forms.Select(choices=[]))
    ip_limit = forms.CharField(required=False, widget=forms.Select(choices=[]))
    paid = forms.BooleanField(required=False, initial=True)
    def clean_usage_limit(self):
        return self.cleaned_data.get('usage_limit')
    def clean_days_limit(self):
        return self.cleaned_data.get('days_limit')
    def clean_ip_limit(self):
        return self.cleaned_data.get('ip_limit')



class ManualSellersCreateConfigForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.username = kwargs.pop('username')
        super().__init__(*args, **kwargs)
    type = forms.ChoiceField(required=False,choices=[('limited','حجمی'),('usage_unlimit', "حجم نامحدود"), ('time_unlimit', "زمان نامحدود")])
    usage_limit = forms.IntegerField(required=False)
    days_limit = forms.IntegerField(required=False)
    ip_limit = forms.ChoiceField(required=False, choices=[(1, '1 کاربره'), (2, '2 کاربره')])
    price = forms.IntegerField(required=False)
    paid = forms.BooleanField(required=False, initial=True)

    def clean_price(self):
        price = self.cleaned_data['price']
        if price is None:
            raise ValidationError('قیمت را وارد کنید.')
        elif not 0 <= price < 1500:
            raise ValidationError('قیمت باید بین 0 تا 1500 هزار تومان باشد.')
        return price

    def clean(self):
        type = self.cleaned_data.get('type')
        usage_limit = self.cleaned_data.get('usage_limit')
        days_limit = self.cleaned_data.get('days_limit')
        if type == "limited":
            if usage_limit is None:
                raise ValidationError('حجم کانفیگ را وارد کنید.')
            elif not 1 < usage_limit < 1000:
                raise ValidationError('حجم کانفیگ باید بین 1 تا 1000 گیگ باشد.')
            if days_limit is None:
                raise ValidationError('مدت زمان کانفیگ را وارد کنید.')
            elif not 0 < days_limit < 365:
                raise ValidationError('مدت زمان کانفیگ باید بین 1 روز تا 365 روز باشد.')
        elif type == 'usage_unlimit':
            if days_limit is None:
                raise ValidationError('مدت زمان کانفیگ را وارد کنید.')
            elif not 0 < days_limit < 365:
                raise ValidationError('مدت زمان کانفیگ باید بین 1 روز تا 365 روز باشد.')
        elif type == 'time_unlimit':
            if usage_limit is None:
                raise ValidationError('حجم کانفیگ را وارد کنید.')
            elif not 1 < usage_limit < 1000:
                raise ValidationError('حجم کانفیگ باید بین 1 تا 1000 گیگ باشد.')



class DisableAllForm(forms.Form):
    @staticmethod
    def sellers_cj():
        l = [(None,"-------")]
        for i in User.objects.filter(level_access__in=[0,1]):
            l.append((i.username, i.username))
        return l

    seller = forms.ChoiceField(required=False, choices=sellers_cj())
    action = forms.ChoiceField(required=False, choices=[(None,"--------"), (0,"Disable ⛔"), (1 , "Enable ✅")])

    def clean(self):
        action = self.cleaned_data.get('action')
        seller = self.cleaned_data.get('seller')

        if seller == "" or action == "":
            raise ValidationError("انتخاب کنید.")

class ChangeInfiniteLimirForm(forms.Form):
    usage_limit = forms.IntegerField(required=False, min_value=0, max_value=10000)

    # def clean_usage_limit(self):
    #     usage_limit = self.cleaned_data.get('usage_limit')
    #
    #     return self.cleaned_data.get('usage_limit')

configs/templates/config_page.html
{% load compress %}
{% load static %}
{% load custom_filters %}

<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'custumers/component.css' %}?{% now "d" %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'configs/config_page.css' %}?{% now "d" %}">
</head>

<body dir="">
    {% include "navbar_bot.html" %}
    {% include 'messages.html' %}
<div id="main">
        <h3 id="conf_name">{{ service.name }}</h3>
        <div id="box0" dir="rtl">
            {% if not service.customer.chat_id %}
                <h3 class="c_info"> یوزر: ---- <a id="u_reg" href=""> Register 🆔</a></h3>
             {% else %}
                <h3 class="c_info">یوزر: <a style="color: white" href="{% url "customers:custumer_detail" service.customer.chat_id %}">{{ service.customer.chat_id }}</a></h3>
            {% endif %}
            <h3 class="c_info">ساخته توسط: {{ service.created_by }}</h3>
        </div>

        {% if service.status == 1 %}
            <h4 id="dis" dir="rtl">⛔ این کانفیگ غیرفعال است. ⛔</h4>
        {% endif %}
        <div id="box1">
            <div class="show_usage">
                {% if service.usage_limit == 0  %}
                    <div class="centering">
                        <h4 class="usage_text">{{ service.usage|floatformat:2 }}GB / <span style="font-size: x-large">∞</span></h4>
                        <div class="progress progressـusage_box">
                            {% if service.start_time == 0 %}
                                <div class="progressـusage progress-bar bg-success" role="progressbar" style="width:100%" aria-confinfonow="100" aria-confinfomin="0" aria-confinfomax="100">Not Started</div>
                            {% else %}
                                <div class="progressـusage progress-bar bg-unlimit" role="progressbar" style="width: 100%" aria-confinfonow="100" aria-confinfomin="0" aria-confinfomax="100">∞</div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="safd">
                        {% if user.level_access == 10 %}
                        <div class="kdfj" >
                            <h3 class="sys_limit">⛔ {{ service.infinit_limit }} GB ⛔ </h3><a style="font-size: x-large" href="{% url "configs:change_unlimit_limit" service.uuid 1 %}">🔏️</a>
                         </div>
                        {% endif %}
                    </div>
                {% else %}
                    {% if service.usage|percent:service.usage_limit > 99 %}
                        <div class="centering">
                            <h4 class="usage_text">{{ service.usage|floatformat:2 }}GB /{{ service.usage_limit }}GB</h4>
                            <div class="progress progressـusage_box">
                                <div class="progressـusage progress-bar bg-danger" role="progressbar" style="width: {{ service.usage|percent:service.usage_limit }}%" aria-confinfonow="{{ service.usage|percent:service.usage_limit }}" aria-confinfomin="0" aria-confinfomax="100">{{ service.usage|percent:service.usage_limit }}%</div>
                            </div>
                        </div>
                    {% elif service.usage|percent:service.usage_limit > 95 %}
                        <div class="centering">
                            <h4 class="usage_text">{{ service.usage|floatformat:2 }}GB /{{ service.usage_limit }}GB</h4>
                            <div class="progress progressـusage_box">
                                <div class="progressـusage progress-bar bg-warning" role="progressbar" style="width: {{ service.usage|percent:service.usage_limit }}%" aria-confinfonow="{{ service.usage|percent:service.usage_limit }}" aria-confinfomin="0" aria-confinfomax="100">{{ service.usage|percent:service.usage_limit }}%</div>
                            </div>
                        </div>
                    {% elif service.usage|percent:service.usage_limit > 0 %}
                        <div class="centering">
                            <h4 class="usage_text">{{ service.usage|floatformat:2 }}GB /{{ service.usage_limit }}GB</h4>
                            <div class="progress progressـusage_box">
                                <div class="progressـusage progress-bar bg-info" role="progressbar" style="width: {{ service.usage|percent:service.usage_limit }}%" aria-confinfonow="{{ service.usage|percent:service.usage_limit }}" aria-confinfomin="0" aria-confinfomax="100">{{ service.usage|percent:service.usage_limit }}%</div>
                            </div>
                        </div>
                    {% else %}
                        <div class="centering">
                            <h4 class="usage_text">{{ service.usage|floatformat:2 }}GB /{{ service.usage_limit }}GB</h4>
                            <div class="progress progressـusage_box">
                                {% if service.start_time == 0  %}
                                    <div class="progressـusage progress-bar bg-success" role="progressbar" style="width:100%" aria-confinfonow="{{ service.3 }}" aria-confinfomin="0" aria-confinfomax="100">Not Started</div>
                                {% else %}
                                    <div class="progressـusage progress-bar bg-info" role="progressbar" style="width:0%" aria-confinfonow="0" aria-confinfomin="0" aria-confinfomax="100">0%</div>
                                {% endif %}
                            </div>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
            <div class="show_time">
                {% if service.expire_time == 0 %}
                    <div class="time">
                        <h4 class="expire_text blue_infinite">⏳ ∞ day</h4>
                    </div>
                {% elif service.start_time == 0 %}
                    <div class="time">
                        <h4 class="expire_text green">⏳ {{ service.expire_time }} d</h4>
                    </div>
                {% elif service.expire_time|dh_int > 3 %}
                    <div class="time">
                        <h4 class="expire_text blue">⏳ {{ service.expire_time|dh }}</h4>
                    </div>
                {% elif service.expire_time|dh_int > 0 %}
                    <div class="time">
                        <h4 class="expire_text orange">⏳ {{ service.expire_time|dh }}</h4>
                    </div>

                {% else %}
                    <div class="time">
                        <h4 class="expire_text red">⏳ {{ service.expire_time|dh }} ago</h4>
                    </div>
                {% endif %}


                <div class="time">
                    {% if service.user_limit == 0 %}
                        <h4 class="expire_text blue">👤 ∞ user</h4>
                    {% else %}
                        <h4 class="expire_text blue">👤 {{ service.user_limit }} user</h4>
                    {% endif %}
            </div>
            </div>

        </div>


        <div id="box2">
            <div>

                <div class="btnslist">
                    <button dir="rtl" class="btn" onclick="copyToClipboard('#bot_link')">📋 دریافت لینک از بات 📋</button>
                </div>

                <div class="btnslist">
                    <button class="btn" onclick="copyToClipboard('#vless')">📡 کپی لینک سابکریپشن 📡</button>
                </div>
                <hr style="width: 100%; background-color: #d8d8d8">
               <div class="btnslist">
                    <button dir="rtl" class="btn" onclick="copyToClipboard('#configs')">📋 کپی کانفیگ ها 📋</button>
                </div>

                <div class="btnslist">
                    <button dir="rtl" class="btn" onclick="copyToClipboard('#configs_qr')">📡 کپی کانفیگ ها با QR_Code 📡</button>
                </div>



                <p hidden id="configs" style="white-space: pre-line;">{{ sub_link_with_name }}</p>
                <p hidden id="configs_qr">{{ qrcode_link }}</p>


                    <p hidden id="vless">{{ sub_link }}</p>
                    <p hidden id="bot_link" style="white-space: pre-line;">{{ get_config_link }}</p>
                <hr style="width: 100%; background-color: #d8d8d8">
                <hr style="width: 100%; background-color: #d6d6d6">
                <div class="conf_btnsbox">
                <a class="conf_btnss tamdid_btn" href="{% url "configs:bot_renew_config" service.uuid "auto" %}"><img class="restart" src="{% static "img/icons8-restart-512.png" %}" alt=""> تمدید </a>
                <a class="conf_btnss change_btn" href="{% url 'configs:bot_change_config' service.uuid %}"><img class="enable" src="{% static "img/setting.png" %}" alt=""> ویرایش </a>
                    {% if service.status == 1 %}
                        <a class="conf_btnss disable_btn" href="{% url 'configs:disable_config' service.uuid 1 %}"><img class="disable" src="{% static "img/enable.png" %}" alt=""> فعال کردن </a>
                    {% else %}
                        <a class="conf_btnss disable_btn" href="{% url 'configs:disable_config' service.uuid 0 %}"><img class="enable" src="{% static "img/disable.png" %}" alt=""> غیرفعال </a>
                    {% endif %}
                <a class="conf_btnss delete_btn" href="{% url 'configs:delete_config' service.uuid %}"><img class="del_img" src="{% static 'img/icons8-delete-64.png' %}" alt=""> حذف </a>
            </div>
            </div>


        </div>

<script>
            function copyToClipboard(element) {
          var $temp = $("<textarea>");
          $("body").append($temp);
          var text = $(element).text();
          $temp.val(text).select();
          document.execCommand("copy");
          $temp.remove();
          alert("با موفقیت کپی شد.");
        }
</script>
{% if config_info %}
            <h4 id="his">History</h4>
            <div class="xcontainer">

		    		<table class="overflow-y">
		    			<thead>
		    				<tr>
                                <th>Data/Time</th>
                                <th>َAction</th>
		    				</tr>
		    			</thead>
		    			<tbody>
                        {% for x in conf_log %}
                            <tr>
                                <td>
                                    {{ x.timestamp|timestamp }}
                                </td>
                                <td dir="ltr">
                                    {{ x.action }}
                                </td>
                            </tr>
                        {% endfor %}
		    			</tbody>
		    		</table>
            </div>
{% endif %}


    </div>
{% include "loading.html" %}

</body>
</html>