SanaeiBot/urls.py
from django.contrib import admin
from django.urls import path, include
from bot import views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webhook/', views.webhook, name='webhook'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path(r'', RedirectView.as_view(url='accounts/home/bot/')),
    path('finance/', include('finance.urls', namespace='finance')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('servers/', include('servers.urls', namespace='servers')),
    path("configs/", include("configs.urls", namespace='configs')),
    path("sellers/",include("sellers.urls", namespace='sellers')),
    path("log/", include("logs.urls", namespace='logs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path("home/bot/", views.HomeBotView.as_view(), name='home_bot'),
    path("home/Sellers/", views.HomeSellersView.as_view(), name='home_sellers'),

    path("settings/", views.SettingsPage.as_view(), name='settings'),
    path("vpn_apps/", views.VpnAppsPage.as_view(), name='vpn_apps'),
    path("delete_app/<int:ind>/", views.DeleteAppPage.as_view(), name='delete_app'),
    path("add_vpn_app/", views.AddAppPage.as_view(), name='add_vpn_app'),
]

bot/urls.py
from django.urls import path
from . import views

app_name = "bot"

urlpatterns = [

]

configs/urls.py
from django.urls import path
from . import views

app_name = "configs"


urlpatterns = [
    path("bot_create_config/<str:form_type>/", views.BotCreateConfigView.as_view(), name="bot_create_config"),
    path("bot_renew_config/<uuid:config_uuid>/<str:form_type>/", views.BotRenewConfigView.as_view(), name="bot_renew_config"),
    path("bot_change_config/<uuid:config_uuid>/", views.BotChangeConfigPage.as_view(), name="bot_change_config"),
    path("bot_list_config/<int:page>/", views.BotListConfigView.as_view(), name="bot_list_config"),
    path("config_page/<str:config_uuid>/", views.ConfigPage.as_view(), name="conf_page"),
    path("client_config_page/<str:config_uuid>/", views.ClientsConfigPage.as_view(), name="client_config_page"),
    path('delete_config/<str:config_uuid>/',views.DeleteConfig.as_view(), name="delete_config"),
    path('disable_config/<str:config_uuid>/<int:enable>/',views.DisableConfig.as_view(), name="disable_config"),
    path("change_unlimit_limit/<uuid:config_uuid>/<int:is_bot>/", views.ChangeUnlimitLimitView.as_view(), name="change_unlimit_limit"),


    path("api_get_config_time_chices/", views.ApiGetConfigTimeChoices.as_view(), name="api_get_time_choices"),
    path("api_get_config_usage_chices/", views.ApiGetConfigUsageChoices.as_view(), name="api_get_usage_choices"),
    path("api_get_config_ip_limit_chices/", views.ApiGetConfigIPLimitChoices.as_view(), name="api_get_iplimit_choices"),
    path("api_get_axact_price/", views.ApiGetConfigPriceChoices.as_view(), name="api_get_axact_price"),


    path("sublink/<uuid:config_uuid>/", views.Sublink.as_view(), name="sublink"),

    path("sellers/create/<str:username>/<str:form_type>/", views.SellersCreateConfigView.as_view(),name="seller_create"),
    path("sellers/list/<str:username>/", views.SellersListConfigView.as_view(),name="seller_list"),
    path("sellers/change_config/<uuid:config_uuid>/", views.SellersChangeConfigPage.as_view(), name="sellers_change_config"),
    path("sellers_config_page/<str:config_uuid>/", views.SellersConfigPage.as_view(), name="sellers_conf_page"),
    path("sellers_renew_page/<str:config_uuid>/<str:form_type>/", views.SellersRenewConfigView.as_view(), name="sellers_renew"),
    path("sellers/disable_all_services/", views.DisableAllService.as_view(), name="sellers_disable_all_services"),


    path("sellers_api_get_config_time_chices/", views.ApiSellersGetConfigTimeChoices.as_view(), name="seller_api_get_time_choices"),
    path("sellers_api_get_config_usage_chices/", views.ApiSellersGetConfigUsageChoices.as_view(), name="seller_api_get_usage_choices"),
    path("sellers_api_get_config_ip_limit_chices/", views.ApiSellersGetConfigIPLimitChoices.as_view(), name="seller_api_get_iplimit_choices"),
    path("sellers_api_get_axact_price/", views.ApiSellersGetConfigPriceChoices.as_view(), name="seller_api_get_axact_price"),

    path("CreateAllConfigsInAllServers/", views.CreateAllConfigsInAllServers.as_view(), name="CreateAllConfigsInAllServers"),


    path("delete_service_by_force/<str:name>/", views.DeleteServiceByForce.as_view(), name="delete_service_by_force"),
]

finance/urls.py
from django.urls import path
from . import views

app_name = "finance"

urlpatterns = [
    path('confirm_payment/<int:show_box>/', views.ConfirmPaymentPage.as_view(), name='confirm_payments'),
    path('first_confirm_payment/<int:obj_id>/', views.FirstConfirmPayment.as_view(), name='first_confirm'),
    path('secoend_confirm_payment/<int:obj_id>/', views.SecondConfirmPayment.as_view(), name='second_confirm'),
    path('deny_payment/<int:obj_id>/', views.DenyPaymentPage.as_view(), name='deny_payments'),
    path('edit_price_payment/<int:obj_id>/<str:typ>/', views.EditPricePayment.as_view(), name='edit_price'),
    path("pay_debts/<uuid:uuid>/<int:action>/", views.PayDebts.as_view(), name='pay_debts'),
    path("bot_pay_history/", views.PayHistory.as_view(), name='bot_pay_history'),

    path('show_prices/', views.ShowPrices.as_view(), name='show_prices'),
    path('delete_or_edit_price/<int:obj_id>/<str:action>/', views.DeleteOrEditPrice.as_view(),
         name='delete_or_edit_price'),
    path('add_price/', views.AddPrice.as_view(), name='add_price'),

    path("sellers_sum_bils/", views.SellersSumBills.as_view(), name='sellers_sum_bils'),
    path("sellers_pay_bill/<str:username>/", views.SellerPayBills.as_view(), name='sellers_pay_bill'),
    path("sellers_delete_pay_bill/<int:id>/", views.SellerDeletePayBills.as_view(), name='sellers_delete_pay_bill'),
    path("select_seller/<str:action>/", views.SelectSeller.as_view(), name='select_seller'),
    path("sellers_show_prices/<str:username>/",views.SellersShowPrices.as_view(), name='sellers_show_prices' ),
    path('seller_delete/<int:obj_id>/', views.SellersDeletePrice.as_view(), name='seller_delete_price'),
    path('seller_add_price/<str:username>/', views.SellersAddPrice.as_view(), name='seller_add_price'),

    path("show_off_codes/", views.ShowOffCodes.as_view(), name='show_off_codes'),
    path("add_off_codes/", views.AddOffCode.as_view(), name='add_off_codes'),
    path("delete_off_code/<str:uuid>/", views.DeleteOffCode.as_view(), name='delete_off_code'),
]

logs/urls.py
from django.urls import path
from . import views

app_name = "logs"

urlpatterns = [
    path("bot_job_queue/", views.BotJobQueueLogView.as_view(), name="bot_job_queue"),
    path("sellers_job_queue/", views.SellersJobQueueLogView.as_view(), name="sellers_job_queue"),
    path("delete_job_queue/<int:id>/", views.DeleteJobQueueView.as_view(), name="delete_job_queue"),
    path("bot_status/", views.BotStatusView.as_view(), name="bot_status"),
    path("sellers_status/", views.SellersStatusView.as_view(), name="sellers_status"),
    path("bot_auto_system_log/", views.BotAutoSystemLog.as_view(), name="bot_auto_system_log"),
    path("sellers_auto_system_log/", views.SellersAutoSystemLog.as_view(), name="sellers_auto_system_log"),

    path("send_msgs_log/", views.SendMsgsLogsView.as_view(), name="send_msgs_log"),
    path("delete_msgs/<str:typ>", views.DeleteMsgView.as_view(), name="delete_msgs"),

    path("report_all/", views.ReportsAll.as_view(), name="report_all"),
    path("report_bot/", views.ReportsBot.as_view(), name="report_bot"),
    path("report_sellers/", views.ReportsSellers.as_view(), name="report_sellers"),

    path("reports_all/api/<str:r_type>/", views.ChartData.as_view()),
]

sellers/urls.py
from django.urls import path
from . import views

app_name = "sellers"

urlpatterns = [
    path("select_seller/<str:action>/", views.SelectSeller.as_view(), name="select_seller"),
    path("sellers_list/", views.SellersList.as_view(), name="sellers_list"),
    path("change_seller_access/<int:seller_id>/", views.ChangeSellerAccesses.as_view(), name="change_seller"),
    path("add_sub_seller/", views.AddSubSeller.as_view(), name="add_sub_seller"),
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser
from django.db import models
from .managers import UserManager
from bot.models import SellerBots



class User(AbstractBaseUser):
    username = models.CharField(unique=True, max_length=20)
    is_active = models.BooleanField(default=True)
    level_access = models.PositiveIntegerField(default=0, choices=[(0, 'Seller'), (1, 'SubSeller'), (10, 'Admin')])
    payment_limit = models.PositiveIntegerField(default=0)
    finance_access = models.BooleanField(default=True)
    create_config_acc = models.BooleanField(default=True)
    list_configs_acc = models.BooleanField(default=True)
    delete_config_acc = models.BooleanField(default=True)
    disable_config_acc = models.BooleanField(default=True)
    bot = models.ForeignKey(SellerBots, on_delete=models.DO_NOTHING, null=True)
    brand = models.CharField(max_length=20, default='Service')


    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ["is_active", "level_access"]  # fields that will show in createsuperuser

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        if self.level_access == 10:
            return True
        return False

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
import json
from .models import User
# from sellers_connection.models import Bots


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='confirm Password', widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['username', 'password', "password2", "level_access"]

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] and cd["password2"] and cd['password'] != cd['password2']:
            raise forms.ValidationError("Passwords must match")
        return cd["password2"]

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(help_text="<a href=\"../password/\">change password</a>")
    class Meta:
        model = User
        fields = ['username', "password", "level_access"]


class LoginForm(forms.Form):
    username = forms.CharField(label="یوزرنیم:")
    password = forms.CharField(widget=forms.PasswordInput(), label="رمز عبور:")

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        if user is None:
            raise ValidationError("یوزرنیم یا پسوورد اشتباه است.")



class AddUserForm(forms.Form):
    username = forms.CharField(max_length=25)
    password = forms.CharField()
    password2 = forms.CharField()

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if " " in username or " " in password:
            raise ValidationError("username or password can not contain space.")

        if not username and not password and not password2:
            raise ValidationError("enter username and password")

        if password != password2:
            raise ValidationError("Passwords must match")

        if User.objects.filter(username=username).exists():
            raise ValidationError("Username already exists")



class ChangeSettingForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        with open("settings.json", "r", encoding="utf-8") as f:
            j = json.load(f)
        self.fields["card_number"].initial = j["pay_card_number"]
        self.fields["card_name"].initial = j["pay_card_name"]
        self.fields["prices_msg_id"].initial = j["prices_msg_id"]
        self.fields["U1_1M"].initial = j["unlimit_limit"]["1u"]["1m"]
        self.fields["U1_2M"].initial = j["unlimit_limit"]["1u"]["2m"]
        self.fields["U1_3M"].initial = j["unlimit_limit"]["1u"]["3m"]
        self.fields["U2_1M"].initial = j["unlimit_limit"]["2u"]["1m"]
        self.fields["U2_2M"].initial = j["unlimit_limit"]["2u"]["2m"]
        self.fields["U2_3M"].initial = j["unlimit_limit"]["2u"]["3m"]
        self.fields["config_name_counter"].initial = j["config_name_counter"]


    card_number = forms.IntegerField()
    card_name = forms.CharField(max_length=25)
    prices_msg_id = forms.IntegerField()
    U1_1M = forms.IntegerField()
    U1_2M = forms.IntegerField()
    U1_3M = forms.IntegerField()
    U2_1M = forms.IntegerField()
    U2_2M = forms.IntegerField()
    U2_3M = forms.IntegerField()
    config_name_counter = forms.IntegerField()


    def clean_card_number(self):
        card_number = self.cleaned_data["card_number"]
        if len(str(card_number)) != 16:
            raise ValidationError("شماره کارت باید 16 رقمی باشد.")
        return card_number

    def clean_config_name_counter(self):
        config_name_counter = self.cleaned_data["config_name_counter"]
        with open("settings.json", "r", encoding="utf-8") as f:
            last = json.load(f)["config_name_counter"]
            if config_name_counter > last:
                return config_name_counter
            else:
                return last + 1


class VpnAppsForm(forms.Form):
    app_name = forms.CharField(max_length=25,required=False)
    download_url = forms.URLField(required=False)
    guid = forms.IntegerField(required=False)

accounts/templates/add_vpn_app.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'create_form.css' %}?{% now "d" %}">
</head>
<body>
{% include "navbar_bot.html" %}
{% include 'messages.html' %}
<div id="main">
        <form novalidate action="" method="post" dir="ltr">
            {% for field_errors in form.errors.values %}
              {% for error in field_errors %}
                  <p dir="rtl" class="errors">{{ error }}</p>
              {% endfor %}
            {% endfor %}
            <h3 id="title">Add Application</h3>
            {% csrf_token %}
            <div id="time_limit" class="textinput item"><h3 class="item_text">App Name: </h3>{{ form.app_name }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">Download Url: </h3>{{ form.download_url }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">Guid Id: </h3>{{ form.guid }}</div>
             <input id="create" type="submit" class="submit_btn" value="Add">
        </form>
    </div>
{% include "loading.html" %}
<style>
    #id_app_name,
    #id_download_url,
    #id_guid {
        width: 100%;
    }
</style>
</body>
</html>

accounts/templates/home_bot.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'home_page.css' %}?{% now "d" %}">
    <script>
        $(document).ready(function() {
            $('#create_config_box').hide()
            $('#list_config_box').hide()
            $('#create_config').click(function () {
                $('#main').hide()
                $('#create_config_box').show()
                }
            )
            $('#list_config').click(function () {
                $('#main').hide()
                $('#list_config_box').show()
                }
            )
            $('.close_btn').click(function () {
                $('#create_config_box').hide()
                $('#list_config_box').hide()
                $('#main').show()
            })
        });
    </script>

</head>

<body dir="rtl">

    <header dir="ltr" class="header">
    <h1 class="logo"><a id="logo" href="{% url 'accounts:home_bot' %}">{{ SITE_NAME }} Telegram BOT</a></h1>
    <ul class="main-nav">
        <div class="dropdown www">
            <h3 dir="rtl" class="dropbtn" id="user boxx" >
                <div class="boz">
                    <span id="username">{{ user.username }}</span>
                    <img id="usericon" src="{% static "img/user.png" %}" alt="user">
                </div>
            </h3>
            <div class="dropdown-content">
                <a href="{% url 'accounts:logout' %}">خروج از حساب</a>
            </div>
        </div>
        <li id="cahnge_li" ><a  class="www" id="home change_a" href='{% url 'accounts:home_sellers' %}'><img
                src="{% static "img/change.png" %}" id="usericon" alt=""> Panel</a></li>

        <style>
            #cahnge_li {
                display: flex;
                flex-direction: row;
                width:35vw;
                justify-content:space-around;
                align-content: center;
                align-items: center;
                justify-items: center;
                padding: 0;
            }
            #change_a {
                width: max-content;
                padding: 0.6rem 0;
                margin: 0;
                align-content: center;
                display:flex;
                flex-direction: row;
                flex-wrap: nowrap;
                text-align: center
            }
        </style>
        <li class="hidephone"><a class="www" href="{% url "configs:bot_create_config" "auto" %}" id="action_create_config">ساخت کانفیگ</a></li>
        <li class="hidephone"><a class="www" href="{% url "configs:bot_list_config" 1 %}" id="action_list_config">لیست کانفیگ ها</a></li>
    </ul>
</header>
    {% include 'messages.html' %}
    <div id="main">
        <div id="box1">
            <div id="searchbox">
                <form novalidate action="{% url "configs:bot_list_config" 1 %}" class="serch_box_inside" method="post">
                    {% csrf_token %}
                    <img class="search_img" src="{% static 'img/search-config.png' %}" alt="search">
                    {{ search_config.search_config }}
                    <input class="input_btn submit_btn" type="submit" value="🔍">
                </form>
                <form novalidate action="{% url "customers:custumers_list" %}" class="serch_box_inside" method="post">
                    {% csrf_token %}
                    <img class="search_img" src="{% static 'img/search-user.png' %}" alt="search">
                    {{ search_customer.search_user }}
                    <input class="input_btn submit_btn" type="submit" value="🔍">
                </form>
            </div>
            <a href="{% url "finance:confirm_payments" 1 %}" class="links link2" id="pay_confirm">✅ تایید پرداخت 💳</a>
            <a href="{% url "configs:bot_create_config" "auto" %}" class="links link2">➕ ساخت کانفیگ 🔗</a>
            <a href="{% url "configs:bot_list_config" 1 %}" class="links link2">📋 لیست کانفیگ ها 🔗</a>
            <a href="{% url "servers:show_servers" %}" class="links" id="servers">🌐 سرور ها 📶</a>
            <a href="{% url 'logs:bot_status' %}" class="links" id="setting">📑 Status 📶</a>
            <a href="{% url "customers:custumers_list" %}" class="links" id="customers">👥 مشتری ها 🤖</a>
{#            <a href="{% url "reports:admin_logs" %}" class="links" id="setting">🗃️ Admin Log 👨🏻‍🔧</a>#}
            <a href="{% url "finance:bot_pay_history" %}" class="links" id="setting">🗃️ Pays Log 💰</a>
{#            <a href="{% url "reports:celery_delete_conf_logs" %}" class="links" id="setting">🗃️ Celery Log 🗑</a>#}
            <a href="{% url "logs:bot_job_queue" %}" class="links" id="setting">🗃️ Job Queue 🗑</a>
            <a href="{% url "logs:bot_auto_system_log" %}" class="links" id="setting">🗃️ AutoSys Log 🗑</a>
            <a href="{% url "logs:send_msgs_log" %}" class="links" id="setting">🗃️ MSG Log 📨</a>
            <a href="{% url 'customers:send_msg_to_all' %}" class="links" id="message">️📝 پیام همگانی 📨</a>
            <a href="{% url "finance:show_prices" %}" class="links" id="tarefeh">💰 تعرفه ها 🛒</a>
            <a href="{% url "logs:report_all" %}" class="links" id="report">📊 گزارشات 📈</a>
            <a href="{% url "finance:show_off_codes" %}" class="links" id="tarefeh">💲 کد تخفیف 🆓</a>
            <a href="{% url "accounts:settings" %}" class="links" id="setting">⚙️ تنظیمات 🛠️</a>
            <a href="{% url 'accounts:vpn_apps' %}" class="links" id="setting">💻 Apps 📱️</a>
{#            <a href="" class="links" id="setting">❗️ Errors ❗️</a>#}
        </div>
    </div>


{% include "loading.html" %}
</body>
</html>

accounts/templates/home_sellers.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'home_page.css' %}?{% now "d" %}">
</head>

<body dir="rtl">
    <header dir="ltr" class="header">
    <h1 class="logo"><a id="logo" href="{% url 'accounts:home_sellers' %}">{{ SITE_NAME }} Panel</a></h1>
    <ul class="main-nav">
        <div class="dropdown www">
            <h3 dir="rtl" class="dropbtn" id="user boxx" >
                <div class="boz">
                    <span id="username">{{ user.username }}</span>
                    <img id="usericon" src="{% static "img/user.png" %}" alt="user">
                </div>
            </h3>
            <div class="dropdown-content">
                <a href="{% url 'accounts:logout' %}">خروج از حساب</a>
            </div>
        </div>
        {% if user.level_access == 10 %}
        <li id="cahnge_li" ><a  class="www" id="home change_a" href='{% url 'accounts:home_bot' %}'><img
                src="{% static "img/change.png" %}" id="usericon" alt=""> TelBot</a></li>
        {% endif %}
        <style>
            #cahnge_li {
                display: flex;
                flex-direction: row;
                width:35vw;
                justify-content:space-around;
                align-content: center;
                align-items: center;
                justify-items: center;
                padding: 0;
            }
            #change_a {
                width: max-content;
                padding: 0.6rem 0;
                margin: 0;
                align-content: center;
                display:flex;
                flex-direction: row;
                flex-wrap: nowrap;
                text-align: center
            }
        </style>
    </ul>
</header>
    {% include 'messages.html' %}
    <div id="main">
        <div id="box1">
            <div id="searchbox">
                <form novalidate action="{% url "configs:seller_list" "all" %}" class="serch_box_inside" method="post">
                    {% csrf_token %}
                    <img class="search_img" src="{% static 'img/search-config.png' %}" alt="search">
                    {{ search_config.search_config }}
                    <input class="input_btn submit_btn" type="submit" value="🔍">
                </form>
            </div>

            {% if user.level_access == 0 %}
                {% if user.create_config_acc and can_buy %}
                    <a href="{% url "configs:seller_create" user.username "auto" %}" class="links link2">➕ ساخت کانفیگ 🔗</a>
                {% else %}
                    <p class="links link2 no_access">➕ ساخت کانفیگ 🔗</p>
                {% endif %}
                {% if user.list_configs_acc %}
                    <a href="{% url "configs:seller_list" user.username %}" class="links link2">📋 لیست کانفیگ ها 🔗</a>
                {% else %}
                    <p class="links link2 no_access">📋 لیست کانفیگ ها 🔗</p>
                {% endif %}
            {% else %}
                {% if user.create_config_acc and can_buy %}
                    <a href="{% url "sellers:select_seller" "create" %}" class="links link2" id="create_config">➕ ساخت کانفیگ 🔗</a>
                {% else %}
                    <p class="links link2 no_access">➕ ساخت کانفیگ 🔗</p>
                {% endif %}
                {% if user.list_configs_acc %}
                    <a href="{% url "sellers:select_seller" "list" %}" class="links link2" id="list_config">📋 لیست کانفیگ ها 🔗</a>
                {% else %}
                    <p class="links link2 no_access">📋 لیست کانفیگ ها 🔗</p>
                {% endif %}
                
            {% endif %}



        {% if user.level_access == 10 %}
            <a href="{% url "finance:sellers_sum_bils" %}" class="links link2" id="customers">💵 صورت حساب 💳</a>
            <a href="{% url 'finance:select_seller' "sellers_show_prices" %}" id="select_prices" class="links">💰 تعرفه ها 🛒</a>
        {% else %}
            {% if user.finance_access %}
                <a href="{% url "finance:sellers_pay_bill" user.username %}" class="links link2" id="customers">💵 صورت حساب 💳</a>
                <a href="{% url 'finance:sellers_show_prices' user.username %}" class="links">💰 تعرفه ها 🛒</a>
            {% else %}
                <p class="links link2 no_access">💵 صورت حساب 💳</p>
                <p class="links  no_access">💰 تعرفه ها 🛒</p>
            {% endif %}
        {% endif %}

            <a href="" class="links" id="setting">🗃️  Logs 👨🏻‍🔧</a>
            <a href="{% url "logs:sellers_job_queue" %}" class="links" id="setting">🗃️ Job Queue 🗑</a>
            <a href="{% url "logs:sellers_auto_system_log" %}" class="links" id="setting">🗃️ AutoSys Log 🗑</a>
            <a href="{% url 'logs:sellers_status' %}" class="links" id="setting">📶 Status 📑</a>
            {% if not user.level_access == 0 %}
                <a href="" class="links" id="message">️📝 پیام همگانی 📨</a>
                <a href="" class="links" id="report">📊 گزارشات 📈</a>
            {% endif %}

        {% if user.level_access == 10 %}
            <a href="{% url "sellers:sellers_list" %}" class="links" id="setting">👤 فروشنده ها 🛠️</a>
            <a href="{% url "configs:sellers_disable_all_services" %}" class="links" id="setting">✅ فعال/غیرفعال سرویس ها ⛔</a>
            <a href="" class="links" id="setting">⚙️ بات تلگرام 🤖️</a>
            <a href="" class="links" id="setting">⚙️ تنظیمات 🛠️</a>
        {% endif %}

        </div>
    </div>
{% include "no_access_popup.html" %}
{% include "loading.html" %}
</body>

</html>