SanaeiBot/urls.py
from django.contrib import admin
from django.urls import path, include
from bot import views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webhook/', views.webhook, name='webhook'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path(r'', RedirectView.as_view(url='accounts/home/bot/')),
    path('finance/', include('finance.urls', namespace='finance')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('servers/', include('servers.urls', namespace='servers')),
    path("configs/", include("configs.urls", namespace='configs')),
    path("sellers/",include("sellers.urls", namespace='sellers')),
    path("log/", include("logs.urls", namespace='logs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path("home/bot/", views.HomeBotView.as_view(), name='home_bot'),
    path("home/Sellers/", views.HomeSellersView.as_view(), name='home_sellers'),

    path("settings/", views.SettingsPage.as_view(), name='settings'),
    path("vpn_apps/", views.VpnAppsPage.as_view(), name='vpn_apps'),
    path("delete_app/<int:ind>/", views.DeleteAppPage.as_view(), name='delete_app'),
    path("add_vpn_app/", views.AddAppPage.as_view(), name='add_vpn_app'),
]

bot/urls.py
from django.urls import path
from . import views

app_name = "bot"

urlpatterns = [

]

configs/urls.py
from django.urls import path
from . import views

app_name = "configs"


urlpatterns = [
    path("bot_create_config/<str:form_type>/", views.BotCreateConfigView.as_view(), name="bot_create_config"),
    path("bot_renew_config/<uuid:config_uuid>/<str:form_type>/", views.BotRenewConfigView.as_view(), name="bot_renew_config"),
    path("bot_change_config/<uuid:config_uuid>/", views.BotChangeConfigPage.as_view(), name="bot_change_config"),
    path("bot_list_config/<int:page>/", views.BotListConfigView.as_view(), name="bot_list_config"),
    path("config_page/<str:config_uuid>/", views.ConfigPage.as_view(), name="conf_page"),
    path("client_config_page/<str:config_uuid>/", views.ClientsConfigPage.as_view(), name="client_config_page"),
    path('delete_config/<str:config_uuid>/',views.DeleteConfig.as_view(), name="delete_config"),
    path('disable_config/<str:config_uuid>/<int:enable>/',views.DisableConfig.as_view(), name="disable_config"),
    path("change_unlimit_limit/<uuid:config_uuid>/<int:is_bot>/", views.ChangeUnlimitLimitView.as_view(), name="change_unlimit_limit"),


    path("api_get_config_time_chices/", views.ApiGetConfigTimeChoices.as_view(), name="api_get_time_choices"),
    path("api_get_config_usage_chices/", views.ApiGetConfigUsageChoices.as_view(), name="api_get_usage_choices"),
    path("api_get_config_ip_limit_chices/", views.ApiGetConfigIPLimitChoices.as_view(), name="api_get_iplimit_choices"),
    path("api_get_axact_price/", views.ApiGetConfigPriceChoices.as_view(), name="api_get_axact_price"),


    path("sublink/<uuid:config_uuid>/", views.Sublink.as_view(), name="sublink"),

    path("sellers/create/<str:username>/<str:form_type>/", views.SellersCreateConfigView.as_view(),name="seller_create"),
    path("sellers/list/<str:username>/", views.SellersListConfigView.as_view(),name="seller_list"),
    path("sellers/change_config/<uuid:config_uuid>/", views.SellersChangeConfigPage.as_view(), name="sellers_change_config"),
    path("sellers_config_page/<str:config_uuid>/", views.SellersConfigPage.as_view(), name="sellers_conf_page"),
    path("sellers_renew_page/<str:config_uuid>/<str:form_type>/", views.SellersRenewConfigView.as_view(), name="sellers_renew"),
    path("sellers/disable_all_services/", views.DisableAllService.as_view(), name="sellers_disable_all_services"),


    path("sellers_api_get_config_time_chices/", views.ApiSellersGetConfigTimeChoices.as_view(), name="seller_api_get_time_choices"),
    path("sellers_api_get_config_usage_chices/", views.ApiSellersGetConfigUsageChoices.as_view(), name="seller_api_get_usage_choices"),
    path("sellers_api_get_config_ip_limit_chices/", views.ApiSellersGetConfigIPLimitChoices.as_view(), name="seller_api_get_iplimit_choices"),
    path("sellers_api_get_axact_price/", views.ApiSellersGetConfigPriceChoices.as_view(), name="seller_api_get_axact_price"),

    path("CreateAllConfigsInAllServers/", views.CreateAllConfigsInAllServers.as_view(), name="CreateAllConfigsInAllServers"),


    path("delete_service_by_force/<str:name>/", views.DeleteServiceByForce.as_view(), name="delete_service_by_force"),
]

customers/urls.py
from django.urls import path
from . import views

app_name = "customers"


urlpatterns = [
   path("custumers_list/", views.CustomerList.as_view(), name="custumers_list"),
   path("custumer_detail/<int:customer_id>/", views.CustomerDetail.as_view(), name="custumer_detail"),
   # path('custumer_configs_api/<str:config_uuid>/', views.GetCustumersConfigsAPI.as_view(), name="custumer_configs_api"),
   path("send_msg_to_all/", views.SendMsgToAllView.as_view(), name="send_msg_to_all"),
   path("send_msg_to_Custumer/<int:customer>/", views.SendMsgToCustomerView.as_view(), name="send_msg_to_customer"),
   path("change_wallet/<int:userid>/", views.ChangeWalletAmount.as_view(), name="change_wallet"),
   # path("update_customer/<int:userid>/", views.UpdateCustumer.as_view(), name="update_customer"),
   # path("register_conf_for_customer/<str:conf_uuid>/", views.RegisterConfigToCustumer.as_view(), name="register_conf_for_customer"),
   # path("ban_user/<int:userid>/<int:status>/", views.BanUser.as_view(), name="ban_user"),
]

finance/urls.py
from django.urls import path
from . import views

app_name = "finance"

urlpatterns = [
    path('confirm_payment/<int:show_box>/', views.ConfirmPaymentPage.as_view(), name='confirm_payments'),
    path('first_confirm_payment/<int:obj_id>/', views.FirstConfirmPayment.as_view(), name='first_confirm'),
    path('secoend_confirm_payment/<int:obj_id>/', views.SecondConfirmPayment.as_view(), name='second_confirm'),
    path('deny_payment/<int:obj_id>/', views.DenyPaymentPage.as_view(), name='deny_payments'),
    path('edit_price_payment/<int:obj_id>/<str:typ>/', views.EditPricePayment.as_view(), name='edit_price'),
    path("pay_debts/<uuid:uuid>/<int:action>/", views.PayDebts.as_view(), name='pay_debts'),
    path("bot_pay_history/", views.PayHistory.as_view(), name='bot_pay_history'),

    path('show_prices/', views.ShowPrices.as_view(), name='show_prices'),
    path('delete_or_edit_price/<int:obj_id>/<str:action>/', views.DeleteOrEditPrice.as_view(),
         name='delete_or_edit_price'),
    path('add_price/', views.AddPrice.as_view(), name='add_price'),

    path("sellers_sum_bils/", views.SellersSumBills.as_view(), name='sellers_sum_bils'),
    path("sellers_pay_bill/<str:username>/", views.SellerPayBills.as_view(), name='sellers_pay_bill'),
    path("sellers_delete_pay_bill/<int:id>/", views.SellerDeletePayBills.as_view(), name='sellers_delete_pay_bill'),
    path("select_seller/<str:action>/", views.SelectSeller.as_view(), name='select_seller'),
    path("sellers_show_prices/<str:username>/",views.SellersShowPrices.as_view(), name='sellers_show_prices' ),
    path('seller_delete/<int:obj_id>/', views.SellersDeletePrice.as_view(), name='seller_delete_price'),
    path('seller_add_price/<str:username>/', views.SellersAddPrice.as_view(), name='seller_add_price'),

    path("show_off_codes/", views.ShowOffCodes.as_view(), name='show_off_codes'),
    path("add_off_codes/", views.AddOffCode.as_view(), name='add_off_codes'),
    path("delete_off_code/<str:uuid>/", views.DeleteOffCode.as_view(), name='delete_off_code'),
]

finance/models.py
from django.db import models
from customers.models import Customer
import uuid
from accounts.models import User


class PurchaseRecord(models.Model):
    created_for = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="P_created_for") # null => bot
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="P_created_by") # null => bot
    service_name = models.CharField(max_length=30, null=True)
    price = models.IntegerField(default=0)
    type = models.SmallIntegerField(default=0, choices=[(0,"buy"), (1,"renew"), (2,"pay")])
    description = models.CharField(max_length=120)
    date_time = models.BigIntegerField(default=0)



class BotPayment(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    price = models.IntegerField()
    action = models.IntegerField() # 0 => add wallet / 1 => buy / 2 => renew
    info = models.JSONField(default=dict)
    image = models.ImageField(upload_to='payment_images/', blank=True, null=True)
    service_uuid = models.UUIDField(null=True)
    status = models.IntegerField()
    # -1 waiting for download pic / 0 waiting for firts confirm /
    # 1 first confirm / 2 second confirm / 9 deny confirm


class Prices(models.Model):
    usage_limit = models.PositiveIntegerField()
    expire_limit = models.PositiveIntegerField()
    price = models.PositiveIntegerField()
    user_limit = models.PositiveIntegerField(default=0)


class OffCodes(models.Model):
    uid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    type_off = models.BooleanField()  # percent = True / amount = False
    amount = models.PositiveIntegerField()
    customer_count = models.PositiveIntegerField()
    use_count = models.PositiveIntegerField()
    create_timestamp = models.PositiveBigIntegerField()
    end_timestamp = models.PositiveBigIntegerField()
    for_infinit_usages = models.BooleanField()
    for_infinit_times = models.BooleanField()
    for_not_infinity = models.BooleanField()


class UserActiveOffCodes(models.Model):
    off_code = models.ForeignKey(OffCodes, on_delete=models.CASCADE)
    custumer = models.ForeignKey(Customer, on_delete=models.DO_NOTHING)
    used = models.BooleanField(default=False)


######################################################  Sellers


class SellersPrices(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    usage_limit = models.PositiveIntegerField()
    expire_limit = models.PositiveIntegerField()
    price = models.PositiveIntegerField()
    user_limit = models.PositiveIntegerField(default=0)

finance/forms.py
from django import forms
from django.core.exceptions import ValidationError

from accounts.models import User
from finance.models import Prices, SellersPrices


class DenyForm(forms.Form):
    reason = forms.CharField(widget=forms.Textarea, max_length=100)
    delete_all_configs = forms.BooleanField(required=False)
    delete_last_config = forms.BooleanField(required=False)
    disable_all_configs = forms.BooleanField(required=False)
    disable_last_config = forms.BooleanField(required=False)
    ban_user = forms.BooleanField(required=False)


class EditPayPriceForm(forms.Form):
    price = forms.IntegerField(required=True,widget=forms.TextInput(attrs={'placeholder': 'قیمت جدید / هزارتومان'}))
    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price:
            if not 5 < price < 999:
                raise ValidationError('قیمت باید بین 5 تا 999 هزار تومان باشد.')
        else:
            raise ValidationError("قیمت را وارد کنید.")
        return price * 1000



class AddPriceForm(forms.Form):
    type_conf = forms.ChoiceField(choices=[("limited", "حجمی"), ("inf_usage", "حجم نامحدود"), ("inf_time", "زمان نامحدود")])
    usage = forms.IntegerField(initial=0)
    month = forms.ChoiceField(choices=[(1,"1 ماه"),(2,"2 ماه"),(3,"3 ماه"),(6,"6 ماه")])
    ip_limit = forms.ChoiceField(choices=[(1,"1 کاربره"),(2,"2 کاربره")])
    price = forms.IntegerField(required=True)

    def clean(self):
        price = self.cleaned_data.get('price')
        usage = self.cleaned_data.get('usage')
        type_conf = self.cleaned_data.get('type_conf')
        ip_limit = self.cleaned_data.get('ip_limit')
        month = self.cleaned_data.get('month')
        if price:
            if not 10 < price < 999 :
                raise ValidationError('قیمت باید بین 10 تا 999 هزار تومان باشد.')
        else:
            raise ValidationError("قیمت را وارد کنید.")
        if type_conf == "limited" or type_conf == 'inf_time':
            if not 2 < usage < 900:
                raise ValidationError("حجم کانفیگ باید بین 2 تا 900 گیگ باشد.")

        if type_conf == "limited":
            ip_limit = 0
        elif type_conf == "inf_usage":
            usage = 0
        elif type_conf == "inf_time":
            month = 0
        if Prices.objects.filter(
                user_limit=int(ip_limit),
                usage_limit=int(usage),
                expire_limit=int(month)).exists():
            raise ValidationError("این تعرفه قبلا ثبت شده است.")

class SellersAddPriceForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.username = kwargs.pop('username', None)
        super().__init__(*args, **kwargs)

    type_conf = forms.ChoiceField(choices=[("limited", "حجمی"), ("inf_usage", "حجم نامحدود"), ("inf_time", "زمان نامحدود")])
    usage = forms.IntegerField(initial=0)
    month = forms.ChoiceField(choices=[(1,"1 ماه"),(2,"2 ماه"),(3,"3 ماه"),(6,"6 ماه")])
    ip_limit = forms.ChoiceField(choices=[(1,"1 کاربره"),(2,"2 کاربره")])
    price = forms.IntegerField(required=True)

    def clean(self):
        price = self.cleaned_data.get('price')
        usage = self.cleaned_data.get('usage')
        type_conf = self.cleaned_data.get('type_conf')
        ip_limit = self.cleaned_data.get('ip_limit')
        month = self.cleaned_data.get('month')
        if price:
            if not 10 < price < 999 :
                raise ValidationError('قیمت باید بین 10 تا 999 هزار تومان باشد.')
        else:
            raise ValidationError("قیمت را وارد کنید.")
        if type_conf == "limited" or type_conf == 'inf_time':
            if not 2 < usage < 900:
                raise ValidationError("حجم کانفیگ باید بین 2 تا 900 گیگ باشد.")

        if type_conf == "limited":
            ip_limit = 0
        elif type_conf == "inf_usage":
            usage = 0
        elif type_conf == "inf_time":
            month = 0
        if SellersPrices.objects.filter(
                seller=User.objects.get(username=self.username),
                user_limit=int(ip_limit),
                usage_limit=int(usage),
                expire_limit=int(month)).exists():
            raise ValidationError("این تعرفه قبلا ثبت شده است.")


class AddOffForm(forms.Form):
    type_off = forms.ChoiceField(choices=[(1, "درصدی (%)"), (0, "مقداری (تومان)")], required=False)
    amount = forms.IntegerField(min_value=1, max_value=50, required=False)
    curumer_count = forms.IntegerField(initial=0, min_value=0 , max_value=500, required=False)
    use_count = forms.ChoiceField(choices=[(1, "1 بار"),(0,"چندین بار")])
    end_time = forms.ChoiceField(choices=[(1,"1 روز"), (2,"2 روز"), (3,"3 روز"), (5,"5 روز"), (7,"7 روز"), (10,"10 روز"), (20,"20 روز"), (30,"30 روز"), (60,"60 روز")], required=False)
    for_infinit_usages = forms.BooleanField(initial=True, required=False)
    for_infinit_times = forms.BooleanField(initial=True, required=False)
    for_not_infinity = forms.BooleanField(initial=True, required=False)

    def clean(self):
        amount = self.cleaned_data.get('amount')
        print(amount)
        if not amount:
            raise ValidationError("مقداد تخفیف را وارد کنید.")


class PriceForm(forms.Form):
    price = forms.IntegerField(initial=0, required=False, max_value=10000)

finance/templates/add_off_code.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'finance/add_price.css' %}?{% now "d" %}">
</head>
<body>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        let type = document.querySelector('#id_type_off');
        let usage = document.querySelector('#typ1');
        let ip_limit = document.querySelector('#typ0');

        function toggleexpireField() {
            if (type.value === '0') {
                usage.style.display = "block"
                ip_limit.style.display = "none"
            }
            else if (type.value === '1'){
                usage.style.display = "none"
                ip_limit.style.display = "block"
            }

        }

        type.addEventListener('change', toggleexpireField);
        toggleexpireField();
    });
</script>
    {% include "navbar_bot.html" %}
    <div id="main">
        <form novalidate action="" method="post" dir="rtl">
            {% for field_errors in form.errors.values %}
              {% for error in field_errors %}
                  <p dir="rtl" class="errors">{{ error }}</p>
              {% endfor %}
            {% endfor %}
            <h3 id="title">کد تخفیف جدید</h3>
            {% csrf_token %}
            <div class="textinput item"><h3 class="item_text">نوع تخفیف : </h3>{{ form.type_off }}</div>
            <div class="textinput item"><h3 class="item_text">مقدار : </h3>{{ form.amount }} <span id="typ0">درصد</span><span id="typ1">هزار تومان</span></div>
            <div class="textinput item"><h3 class="item_text"> تعداد یوزر هایی که میتوانند استفاده کنند : </h3>{{ form.curumer_count }} <span style="display: block"> 0 = تعداد نامحدود </span></div>
            <div class="textinput item"><h3 class="item_text"> تعداد دفعاتی که هر یوزر میتواند استفاده کند : </h3>{{ form.use_count }}</div>
            <div class="textinput item"><h3 class="item_text">مدت زمان اجازه ثبت : </h3>{{ form.end_time }}</div>
            <div class="textinput item"><h3 class="item_text">کانفیک های حجمی : </h3>{{ form.for_not_infinity }}</div>
            <div class="textinput item"><h3 class="item_text">کانفیک های حجم نامحدود : </h3>{{ form.for_infinit_usages }}</div>
            <div class="textinput item"><h3 class="item_text">کانفیک های زمان نامحدود : </h3>{{ form.for_infinit_times }}</div>

            <input id="create" type="submit" value="Create" class="submit_btn">
        </form>
    </div>
{% include "loading.html" %}
    <style>
        #id_amount,#id_type_off, #id_curumer_count, #id_use_count, #id_end_time {
            width: 50%;
            text-align: center;
        }
        #id_for_not_infinity, #id_for_infinit_usages, #id_for_infinit_times {
            width: 1rem;
            height: 2rem;
            margin-top: 0;
        }
    </style>

</body>
</html>

finance/templates/confirm_payment.html
{% load compress %}
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'finance/confirm_payment.css' %}?{% now "d" %}">
    <script>
        $(document).ready(function() {
            $("#loading").hide()
            $(".item").click(function () {
                $("#main").hide();
                $("#loading").show();
            });
        });
    </script>
    <script>
        $(document).ready(function() {
            {% if show_box == 1 %}
                $("#box1").show();
                $("#box2").hide();
                $("#box3").hide();
                $("#btn1").css({"background-color": "#000d3f", "color":"white"})
                $("#btn2").css({"background-color": "white", "color":"#000d3f"})
                $("#btn3").css({"background-color": "white", "color":"#000d3f"})
            {% elif show_box == 2 %}
                $("#box1").hide();
                $("#box2").show();
                $("#box3").hide();
                $("#btn1").css({"background-color": "white", "color":"#000d3f"})
                $("#btn2").css({"background-color": "#000d3f", "color":"white"})
                $("#btn3").css({"background-color": "white", "color":"#000d3f"})
            {% elif show_box == 3 %}
                $("#box1").hide();
                $("#box2").hide();
                $("#box3").show();
                $("#btn1").css({"background-color": "white", "color":"#000d3f"})
                $("#btn2").css({"background-color": "white", "color":"#000d3f"})
                $("#btn3").css({"background-color": "#000d3f", "color":"white"})
            {% endif %}


            $("#btn1").click(function () {
                $("#box1").show();
                $("#box2").hide();
                $("#box3").hide();
                $("#btn1").css({"background-color": "#000d3f", "color":"white"})
                $("#btn2").css({"background-color": "white", "color":"#000d3f"})
                $("#btn3").css({"background-color": "white", "color":"#000d3f"})
            });
            $("#btn2").click(function () {
                $("#box1").hide();
                $("#box2").show();
                $("#box3").hide();
                $("#btn1").css({"background-color": "white", "color":"#000d3f"})
                $("#btn2").css({"background-color": "#000d3f", "color":"white"})
                $("#btn3").css({"background-color": "white", "color":"#000d3f"})
            });
            $("#btn3").click(function () {
                $("#box1").hide();
                $("#box2").hide();
                $("#box3").show();
                $("#btn1").css({"background-color": "white", "color":"#000d3f"})
                $("#btn2").css({"background-color": "white", "color":"#000d3f"})
                $("#btn3").css({"background-color": "#000d3f", "color":"white"})
            });
        });
    </script>
</head>
<body>
    {% include "navbar_bot.html" %}
    {% include 'messages.html' %}
    <div id="main">
        <div id="changebox" dir="rtl">
            <button class="changebtns" id="btn1"> تایید پرداخت<span class="number_not">{{ confirm_count }}</span></button>
            <button class="changebtns" id="btn2"> تایید نهایی <span class="number_not">{{ second_confirm_count }}</span></button>
            <button class="changebtns" id="btn3"> پرداخت بدهی<span class="number_not">{{ not_paid_count }}</span></button>
        </div>
        <div id="box1">
            {% for i in confirm %}
                <div class="paybox" >
                    <div class="pay_info">
                        <div class="infobox">
                            {% if i.action == 1 %}
                                <h4 class="info">Buy Service</h4>
                            {% elif i.action == 0 %}
                                <h4 class="info">Add to Wallet</h4>
                            {% else %}
                            <h4 class="info">Renew: <a style="color: #98e2ff" href="{% url "customers:custumer_detail" i.customer.chat_id %}">{{ i.info.service_uuid|get_conf_name }}</a></h4>
                            {% endif %}
                            <h3 class="info">userid: <a href="" style="color: #98e2ff">{{ i.customer.chat_id }}</a></h3>
                            <h3 class="info">price : <span class="nspan">{{ i.price }} T</span></h3>

                        </div>
                        <div class="conf_btns">

                            <div class="confirmbtn">
                                <a href="{% url 'finance:first_confirm' i.id %}" class="confirm c_btnd">تایید اولیه</a>
                            </div>
                            <div class="confirmbtn">
                                <a href="{% url 'finance:second_confirm' i.id %}" class="sec_confirm c_btnd">تایید نهایی</a>
                            </div>
                            <div class="confirmbtn">
                                <a href="{% url 'finance:edit_price' i.id "buy" %}" class="edit_price c_btnd">تغییر قیمت</a>
                            </div>
                            <div class="confirmbtn">
                                <a href="{% url 'finance:deny_payments' i.id %}" class="deny c_btnd">عدم تایید</a>
                            </div>
                        </div>
                    </div>
                    <img class="pay_img" src="{{ i.image.url }}" alt="pay_img">
                </div>
            {% endfor %}

        </div>
        <div id="box2">
            {% for i in second_confirm %}
                <div class="paybox" >
                    <div class="pay_info">
                        <div class="infobox">
                            {% if not i.customer.chat_id %}
                                <h3 class="info">userid: ------</h3>
                            {% else %}
                                <h3 class="info">userid:<a style="color: #98e2ff" href="{% url 'customers:custumer_detail' i.customer.chat_id %}">{{ i.customer.chat_id }}</a></h3>
                            {% endif %}
                            <h3 class="info">price : <span class="nspan">{{ i.price|price }} T</span></h3>

                        </div>
                        <div class="conf_btns">
                            <div class="confirmbtn">
                                <a href="{% url 'finance:second_confirm' i.id %}" class="sec_confirm c_btnd">تایید نهایی</a>
                            </div>
                            <div class="confirmbtn">
                                <a href="{% url 'finance:deny_payments' i.id %}" class="deny c_btnd">عدم تایید و حذف</a>
                            </div>
                        </div>
                    </div>
                    <img class="pay_img" src="{{ i.image.url }}" alt="pay_img">
                </div>
            {% endfor %}

        </div>

        <div id="box3">
            {% for i in not_paid %}
                <div class="xy">
                    <div class="fbox">
                        <a href="{% url "configs:conf_page" i.uuid %}" class="notpaid_text">Service: <span class="nspan" style="color: #98E2FFFF">{{ i.name }}</span> </a>
                        <h3 class="notpaid_text">price:  <span class="nspan">{{ i.price }} T</span></h3>
                        {% if not i.customer.chat_id %}
                            <h3 class="notpaid_text">user:  <span class="nspan">----</span></h3>
                        {% else %}
                            <a href="{% url "customers:custumer_detail" i.customer.chat_id %}" class="notpaid_text">user:  <span style="color: #98E2FFFF" class="nspan">{{ i.customer.chat_id }}</span></a>
                        {% endif %}
                        {% if i.status == 1 %}
                            <h3 dir="rtl" style="background-color: aliceblue; color: red; text-align: center" class="notpaid_text">سرویس غیرفعال است.</h3>
                        {% endif %}
                    </div>
                    <div class="pbox">
                        <a href="{% url "finance:pay_debts" i.uuid 0 %}" class="confirm x_btnd">پرداخت شده</a>
                        {% if not i.status == 1 %}
                            <a href="{% url "finance:pay_debts" i.uuid 1 %}" class="disable x_btnd">غیرفعال کانفیگ</a>
                        {% endif %}
                        <a href="{% url "finance:pay_debts" i.uuid 2 %}" class="deny x_btnd">حذف کانفیگ</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% include "loading.html" %}

</body>
</html>

finance/templates/subsellers_list_finance.html
{% load static %}
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'home_page.css' %}?{% now "d" %}">
</head>
<body>
    {% include "navbar_sellers.html" %}

    <div class="servers" id="list_config_box">
        <div class="closebox"><a href="{% url "accounts:home_sellers" %}" class="close_btn">✖️</a></div>
        {% if action == "show_prices" %}
            <h2>تعرفه ها</h2>
        {% endif %}
    <div class="server_lists" >
        {% if user.level_access == 1 %}
        <a class="server_name" href='/finance/{{ action }}/{{ user.username }}'>{{ user.username }} 👤</a>
        {% endif %}
        {% for s in sellers_list %}
            <a class="server_name" href='/finance/{{ action }}/{{ s.username }}'>{{ s.username }} 👤</a>
        {% endfor %}
        </div>
    </div>

</body>